"""add campos de bloqueio de login no Usuario

Revision ID: dd521f39cdfb
Revises: 001_initial_schema
Create Date: 2026-09-09 22:48:55.786385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd521f39cdfb'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('tentativasFalhas', sa.Integer(), nullable=False))
    op.add_column('Usuarios', sa.Column('bloqueadoAte', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuarios', 'bloqueadoAte')
    op.drop_column('Usuarios', 'tentativasFalhas')
    
    # ### end Alembic commands ###
