name: CI - Backend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  test-dev:
    name: Lint & Test (Dev)
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/dev' || github.base_ref == 'develop' || github.base_ref == 'dev' || github.head_ref == 'develop' || github.head_ref == 'dev'
    runs-on: ubuntu-latest
    environment: Devlopment

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL || vars.DATABASE_URL || 'sqlite:///./fastcooking_ci_dev.db' }}
      SECRET_KEY: ${{ secrets.SECRET_KEY || vars.SECRET_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET || vars.JWT_SECRET }}
      BCRYPT_ROUNDS: ${{ vars.BCRYPT_ROUNDS || secrets.BCRYPT_ROUNDS || '12' }}
      SERVER_PORT: ${{ vars.SERVER_PORT || secrets.SERVER_PORT || '8000' }}
      APP_ENV: ${{ vars.APP_ENV || 'development' }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install ruff pytest

      - name: Rodar lint
        run: ruff check .

      - name: Rodar testes
        run: pytest -W ignore

  test-prod:
    name: Lint & Test (Prod)
    if: (github.ref == 'refs/heads/main' || github.base_ref == 'main') && !(github.head_ref == 'develop' || github.head_ref == 'dev')
    runs-on: ubuntu-latest
    environment: Production

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL || vars.DATABASE_URL || 'sqlite:///./fastcooking_ci_prod.db' }}
      SECRET_KEY: ${{ secrets.SECRET_KEY || vars.SECRET_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET || vars.JWT_SECRET }}
      BCRYPT_ROUNDS: ${{ vars.BCRYPT_ROUNDS || secrets.BCRYPT_ROUNDS || '12' }}
      SERVER_PORT: ${{ vars.SERVER_PORT || secrets.SERVER_PORT || '8000' }}
      APP_ENV: ${{ vars.APP_ENV || 'production' }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install ruff pytest

      - name: Rodar lint
        run: ruff check .

      - name: Rodar testes
        run: pytest
